services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: estoria
      POSTGRES_PASSWORD: estoria
      POSTGRES_DB: estoria
    ports:
      - "5432:5432"
    networks:
      - estoria-net
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  estoria-net:
    driver: bridge

volumes:
  postgres_data:
